### ISSUE TITLE
[TODO] TileEntity bugs

### ISSUE THREAD

**Issue by Takakura-Anri** [ProjectUranus/FoodCraft-Reloaded#1]
- [x] Fluid Tank data not being saved/loaded
I doubt it is a FluidTank implementation error
- [x] Progress data not being saved/loaded
Seems related with recipe related bugs
- [x] Machine not auto starting after the save game is loaded
Possible solution: sort out all occasions machines should look up a recipe
- [x] Heat binding when world is loaded
Possible solution: auto-bind them in TileEntity#validate
