### ISSUE TITLE
[TODO] Container bugs

### ISSUE THREAD

**Issue by Takakura-Anri** [ProjectUranus/FoodCraft-Reloaded#2]
- [x] Cleanup unnecessary text tooltips
Existed in WidgetProgressBar and WidgetHeat
- [x] Text Tooltips I18n
- [ ] Cleanup unnecessary synchronization of recipe
Recipes are final in a game session, thus recipe's progress data is redundant
However, client needs a better method to predict machine behaviour
- [ ] Find out lags in Gui and networking
- [ ] Shift-clicking ability
    - [ ] Beverage Making
    - [ ] Brew Barrel
    - [ ] Chopping Board
    - [ ] Frying Pan
    - [ ] Mill
    - [ ] Pan
    - [ ] Pot
    - [ ] Pressure Cooker
    - [X] Stove
