### ISSUE TITLE
[TODO] Interoperability

### ISSUE THREAD

**Issue by Takakura-Anri** [ProjectUranus/FoodCraft-Reloaded#3]
- [ ] Redstone control
    - [ ] Controls heat mode
    Three modes of heat mode that shall be implemented: normal, stop, rapid(2x faster but 3x costs)
    - [ ] Heat comparator output scaled in minimum heat and maximum heat

- [x] The One Probe Integration
    - [x] Heat Info
    - [x] Progress Info
The One Probe Integration requires a huge amount of packets more, but we still have to support it

- [x] Just Enough Items Integration
    - [X] Recipes
    - [x] Auto-crafting
